language: python
python:
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - pip install -r requirements.txt

script:
    - py.test
    - python main.py
    - py.test --cov-report html --cov-fail-under 80 --cov .

after_success:
    - codecov
